version: '3.7'

services:
  deliveggie.webapi: 
    build:
      context: .
      dockerfile: DeliVeggie.WebAPI/Dockerfile      
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5010:5000"
    networks:
      - deliveggienet
      
  mongo:
    image: mongo
    restart: always
    volumes:
      - C:\Projekte\Assessment\MongoDB\Data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: xcelsus4132
    ports:
      - "27017:27017"
    networks:
      - deliveggienet

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: xcelsus4132
    networks:
      - deliveggienet


      ### RabbitMQ is missing here

networks:
  deliveggienet:
    driver: bridge